server {
    listen 80;
    listen [::]:80;
    server_name 64.226.76.174;

    client_max_body_size 55M;
    proxy_headers_hash_max_size 1024;
    proxy_headers_hash_bucket_size 128;

    location /static/ {
        alias /opt/medclinic/staticfiles/;
        access_log off;
        expires 7d;
    }

    location /media/ {
        alias /opt/medclinic/media/;
        access_log off;
        expires 1d;
    }

    location / {
        include proxy_params;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/run/medclinic/gunicorn.sock;
    }
}
