# Generated by Django 6.0.6 on 2026-07-04 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_workschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Введите телефон в формате +380XXXXXXXXX.', regex='^\\+?\\d[\\d\\s().-]{7,18}$')]),
        ),
    ]
