# Generated by Django 6.0.6 on 2026-07-11 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_slots',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.medicalservice'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Нова заявка'), ('approved', 'Підтверджено'), ('completed', 'Завершено'), ('canceled', 'Скасовано'), ('rejected', 'Відхилено')], default='pending', max_length=20),
        ),
    ]
