# Generated by Django 6.0.6 on 2026-07-11 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_appointment_approved_at_appointment_duration_slots_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_appointment_slot',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['canceled', 'rejected']), _negated=True), fields=('doctor', 'date', 'time'), name='unique_active_appointment_slot'),
        ),
    ]
