# Generated by Django 6.0.6 on 2026-07-11 08:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_remove_appointment_unique_active_appointment_slot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Запис на прийом', 'verbose_name_plural': 'Записи на прийом'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Лікар', 'verbose_name_plural': 'Лікарі'},
        ),
        migrations.AlterModelOptions(
            name='medicalservice',
            options={'ordering': ['name'], 'verbose_name': 'Медична послуга', 'verbose_name_plural': 'Медичні послуги'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Графік лікаря', 'verbose_name_plural': 'Графіки лікарів'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'Пацієнт'), ('doctor', 'Лікар')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, 'Пʼятниця'), (5, 'Субота'), (6, 'Неділя')]),
        ),
        migrations.CreateModel(
            name='DoctorPatientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=80)),
                ('patient_last_name', models.CharField(blank=True, max_length=80)),
                ('patient_phone', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Введите телефон в формате +380XXXXXXXXX.', regex='^\\+?\\d[\\d\\s().-]{7,18}$')])),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_cards', to='clinic.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Картка пацієнта',
                'verbose_name_plural': 'Картки пацієнтів',
                'ordering': ['patient_last_name', 'patient_first_name'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'patient_phone'), name='unique_doctor_patient_phone_card')],
            },
        ),
    ]
