# Generated by Django 6.0.6 on 2026-07-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_clinicsettings_galleryimage_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='home_effect',
            field=models.CharField(choices=[('none', 'Без анімації'), ('teeth', 'Літаючі зуби'), ('crosses', 'Медичні хрестики')], default='none', max_length=20),
        ),
    ]
