# Generated by Django 6.0.6 on 2026-07-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_clinicsettings_home_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='particle_image',
            field=models.ImageField(blank=True, upload_to='clinic/branding/particles/'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='home_effect',
            field=models.CharField(choices=[('none', 'Без анімації'), ('teeth', 'Літаючі зуби'), ('crosses', 'Медичні хрестики'), ('custom', 'Власне зображення')], default='none', max_length=20),
        ),
    ]
