# Generated by Django 6.0.6 on 2026-07-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_clinicsettings_particle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='home_effect',
            field=models.CharField(choices=[('none', 'Без анімації'), ('teeth', 'Літаючі зуби'), ('crosses', 'Медичні хрестики'), ('custom', 'Власне зображення'), ('dental_field', 'Стоматологічне поле')], default='none', max_length=20),
        ),
    ]
