# Generated by Django 6.0.6 on 2026-07-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_alter_clinicsettings_home_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Нотатка'), ('examination', 'Огляд'), ('treatment', 'Лікування'), ('recommendation', 'Рекомендації')], default='note', max_length=24)),
                ('title', models.CharField(max_length=180)),
                ('details', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_entries', to='clinic.appointment')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_entries', to='clinic.doctorpatientcard')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_record_entries', to='clinic.doctor')),
            ],
            options={
                'verbose_name': 'Запис у картці пацієнта',
                'verbose_name_plural': 'Записи у картках пацієнтів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patient_records/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clinic.patientrecordentry')),
            ],
            options={
                'verbose_name': 'Фото медичного запису',
                'verbose_name_plural': 'Фото медичних записів',
            },
        ),
    ]
