# Generated by Django 6.0.6 on 2026-07-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_patientrecordentry_patientrecordimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes_exact',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='break_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
