# Generated by Django 6.0.6 on 2026-07-14 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_appointment_duration_minutes_exact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='appointment_images/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clinic.appointment')),
            ],
            options={
                'verbose_name': 'Фото до заявки',
                'verbose_name_plural': 'Фото до заявок',
            },
        ),
    ]
