# Generated by Django 6.0.6 on 2026-07-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_medicalservice_is_patient_selectable'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalservice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MedicalServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clinic.medicalservice')),
            ],
            options={
                'verbose_name': 'Фотографія послуги',
                'verbose_name_plural': 'Фотографії послуг',
                'ordering': ['id'],
            },
        ),
    ]
