# Generated by Django 6.0.6 on 2026-07-18 20:24

import django.db.models.deletion
from django.db import migrations, models


def create_workplaces_from_schedules(apps, schema_editor):
    DoctorWorkplace = apps.get_model('clinic', 'DoctorWorkplace')
    WorkSchedule = apps.get_model('clinic', 'WorkSchedule')

    doctor_ids = (
        WorkSchedule.objects.order_by()
        .values_list('doctor_id', flat=True)
        .distinct()
    )
    for doctor_id in doctor_ids:
        places = {}
        schedules = WorkSchedule.objects.filter(doctor_id=doctor_id).order_by('weekday', 'id')
        for schedule in schedules:
            if not schedule.city and not schedule.address:
                continue
            key = (schedule.city, schedule.address)
            if key not in places:
                number = len(places) + 1
                name = 'Основне місце прийому' if number == 1 else f'Місце прийому {number}'
                places[key] = DoctorWorkplace.objects.create(
                    doctor_id=doctor_id,
                    name=name,
                    city=schedule.city or 'Місто не вказано',
                    address=schedule.address or 'Адресу не вказано',
                )
            schedule.workplace_id = places[key].id
            schedule.save(update_fields=['workplace'])


def remove_migrated_workplaces(apps, schema_editor):
    WorkSchedule = apps.get_model('clinic', 'WorkSchedule')
    DoctorWorkplace = apps.get_model('clinic', 'DoctorWorkplace')
    WorkSchedule.objects.update(workplace=None)
    DoctorWorkplace.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_rename_price_to_approximate_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorWorkplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='clinic.doctor')),
            ],
            options={
                'verbose_name': 'Місце прийому',
                'verbose_name_plural': 'Місця прийому',
                'ordering': ['name', 'city', 'address'],
            },
        ),
        migrations.AddField(
            model_name='workschedule',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='clinic.doctorworkplace'),
        ),
        migrations.RunPython(
            create_workplaces_from_schedules,
            remove_migrated_workplaces,
        ),
        migrations.AddConstraint(
            model_name='doctorworkplace',
            constraint=models.UniqueConstraint(fields=('doctor', 'name'), name='unique_doctor_workplace_name'),
        ),
    ]
