# Generated by Django 6.0.6 on 2026-07-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_doctorworkplace_workschedule_workplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='previous_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='previous_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Нова заявка'), ('approved', 'Підтверджено'), ('completed', 'Завершено'), ('canceled', 'Скасовано'), ('rejected', 'Відхилено'), ('reschedule_proposed', 'Очікує рішення пацієнта')], default='pending', max_length=20),
        ),
    ]
