# Generated by Django 6.0.6 on 2026-07-18 22:05

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0022_appointment_previous_date_appointment_previous_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Підтверджено'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Дата прийому'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.doctor', verbose_name='Лікар'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes_exact',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Тривалість прийому, хвилин'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_slots',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кількість слотів'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Зареєстрований пацієнт'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Електронна пошта пацієнта'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_first_name',
            field=models.CharField(max_length=80, verbose_name="Ім'я пацієнта"),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_last_name',
            field=models.CharField(max_length=80, verbose_name='Прізвище пацієнта'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Введіть телефон у форматі +380XXXXXXXXX.', regex='^\\+?\\d[\\d\\s().-]{7,18}$')], verbose_name='Телефон пацієнта'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='previous_date',
            field=models.DateField(blank=True, null=True, verbose_name='Попередня дата'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='previous_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Попередній час'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(verbose_name='Причина звернення'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reschedule_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запропоновано перенесення'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.medicalservice', verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Нова заявка'), ('approved', 'Підтверджено'), ('completed', 'Завершено'), ('canceled', 'Скасовано'), ('rejected', 'Відхилено'), ('reschedule_proposed', 'Очікує рішення пацієнта')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Час прийому'),
        ),
        migrations.AlterField(
            model_name='appointmentimage',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clinic.appointment', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='appointmentimage',
            name='image',
            field=models.ImageField(upload_to='appointment_images/%Y/%m/', verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='appointmentimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Завантажено'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='clinic_name',
            field=models.CharField(default='MedClinic', max_length=120, verbose_name='Назва клініки'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='home_background',
            field=models.ImageField(blank=True, upload_to='clinic/branding/', verbose_name='Фон сайту'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='home_effect',
            field=models.CharField(choices=[('none', 'Без анімації'), ('teeth', 'Літаючі зуби'), ('crosses', 'Медичні хрестики'), ('custom', 'Власне зображення'), ('dental_field', 'Стоматологічне поле')], default='none', max_length=20, verbose_name='Анімований ефект'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='clinic/branding/', verbose_name='Логотип клініки'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='particle_image',
            field=models.ImageField(blank=True, upload_to='clinic/branding/particles/', verbose_name='Зображення частинок'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Інформація про лікаря'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Введіть телефон у форматі +380XXXXXXXXX.', regex='^\\+?\\d[\\d\\s().-]{7,18}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='doctor_photos/', verbose_name='Фото лікаря'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_url',
            field=models.URLField(blank=True, verbose_name='Посилання на фото'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=120, verbose_name='Спеціальність'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='doctorpatientcard',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_cards', to='clinic.doctor', verbose_name='Лікар'),
        ),
        migrations.AlterField(
            model_name='doctorpatientcard',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Нотатки лікаря'),
        ),
        migrations.AlterField(
            model_name='doctorpatientcard',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_cards', to=settings.AUTH_USER_MODEL, verbose_name='Зареєстрований пацієнт'),
        ),
        migrations.AlterField(
            model_name='doctorpatientcard',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Електронна пошта пацієнта'),
        ),
        migrations.AlterField(
            model_name='doctorpatientcard',
            name='patient_first_name',
            field=models.CharField(max_length=80, verbose_name="Ім'я пацієнта"),
        ),
        migrations.AlterField(
            model_name='doctorpatientcard',
            name='patient_last_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Прізвище пацієнта'),
        ),
        migrations.AlterField(
            model_name='doctorpatientcard',
            name='patient_phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Введіть телефон у форматі +380XXXXXXXXX.', regex='^\\+?\\d[\\d\\s().-]{7,18}$')], verbose_name='Телефон пацієнта'),
        ),
        migrations.AlterField(
            model_name='doctorpatientcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='doctorworkplace',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='doctorworkplace',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='doctorworkplace',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='clinic.doctor', verbose_name='Лікар'),
        ),
        migrations.AlterField(
            model_name='doctorworkplace',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Назва клініки або кабінету'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='clinic/gallery/', verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Підпис до фото'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='approximate_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Орієнтовна вартість'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис послуги'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinic.doctor', verbose_name='Лікар'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='is_patient_selectable',
            field=models.BooleanField(default=True, verbose_name='Доступна для онлайн-запису'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Назва послуги'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок відображення'),
        ),
        migrations.AlterField(
            model_name='medicalserviceimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Додано'),
        ),
        migrations.AlterField(
            model_name='medicalserviceimage',
            name='image',
            field=models.ImageField(upload_to='service_photos/', verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='medicalserviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clinic.medicalservice', verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='clinic.doctor', verbose_name='Лікар'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, upload_to='clinic/news/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=models.TextField(verbose_name='Текст новини'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='patientrecordentry',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_entries', to='clinic.appointment', verbose_name='Прийом'),
        ),
        migrations.AlterField(
            model_name='patientrecordentry',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_entries', to='clinic.doctorpatientcard', verbose_name='Картка пацієнта'),
        ),
        migrations.AlterField(
            model_name='patientrecordentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='patientrecordentry',
            name='details',
            field=models.TextField(verbose_name='Детальна інформація'),
        ),
        migrations.AlterField(
            model_name='patientrecordentry',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_record_entries', to='clinic.doctor', verbose_name='Лікар'),
        ),
        migrations.AlterField(
            model_name='patientrecordentry',
            name='kind',
            field=models.CharField(choices=[('note', 'Нотатка'), ('examination', 'Огляд'), ('treatment', 'Лікування'), ('recommendation', 'Рекомендації')], default='note', max_length=24, verbose_name='Тип запису'),
        ),
        migrations.AlterField(
            model_name='patientrecordentry',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='Рекомендації пацієнту'),
        ),
        migrations.AlterField(
            model_name='patientrecordentry',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='patientrecordentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='patientrecordimage',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clinic.patientrecordentry', verbose_name='Медичний запис'),
        ),
        migrations.AlterField(
            model_name='patientrecordimage',
            name='image',
            field=models.ImageField(upload_to='patient_records/%Y/%m/', verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='patientrecordimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Завантажено'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Введіть телефон у форматі +380XXXXXXXXX.', regex='^\\+?\\d[\\d\\s().-]{7,18}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='patient_photos/', verbose_name='Фото профілю'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'Пацієнт'), ('doctor', 'Лікар')], max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='break_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Тривалість обіду, хвилин'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Початок обідньої перерви'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinic.doctor', verbose_name='Лікар'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Кінець прийому'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Робочий день'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='slot_minutes',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Тривалість слота, хвилин'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Початок прийому'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, 'Пʼятниця'), (5, 'Субота'), (6, 'Неділя')], verbose_name='День тижня'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='clinic.doctorworkplace', verbose_name='Місце прийому'),
        ),
    ]
