# Generated by Django 6.0.6 on 2026-07-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0023_ukrainian_admin_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Підпис для адміністратора')),
                ('image', models.ImageField(upload_to='clinic/hero/', verbose_name='Фотографія')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати у верхньому слайдері')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Фото верхнього слайдера',
                'verbose_name_plural': 'Фото верхнього слайдера',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
