# Generated by Django 6.0.6 on 2026-07-20 16:59

import clinic.storage
import clinic.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0024_homeheroslide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(storage=clinic.storage.PrivateMediaStorage(), upload_to='appointment_videos/%Y/%m/', validators=[clinic.validators.validate_video_upload], verbose_name='Відео')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено')),
            ],
            options={
                'verbose_name': 'Відео до заявки',
                'verbose_name_plural': 'Відео до заявок',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='Дія')),
                ('target_type', models.CharField(max_length=80, verbose_name='Тип об’єкта')),
                ('target_id', models.CharField(blank=True, max_length=80, verbose_name='Ідентифікатор об’єкта')),
                ('target_label', models.CharField(blank=True, max_length=240, verbose_name='Назва об’єкта')),
                ('details', models.TextField(blank=True, verbose_name='Деталі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
            ],
            options={
                'verbose_name': 'Подія журналу',
                'verbose_name_plural': 'Журнал дій',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='service_videos/', validators=[clinic.validators.validate_video_upload], verbose_name='Відео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
            ],
            options={
                'verbose_name': 'Відео послуги',
                'verbose_name_plural': 'Відео послуг',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PatientRecordVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(storage=clinic.storage.PrivateMediaStorage(), upload_to='patient_record_videos/%Y/%m/', validators=[clinic.validators.validate_video_upload], verbose_name='Відео')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено')),
            ],
            options={
                'verbose_name': 'Відео медичного запису',
                'verbose_name_plural': 'Відео медичних записів',
            },
        ),
        migrations.AlterField(
            model_name='appointmentimage',
            name='image',
            field=models.ImageField(storage=clinic.storage.PrivateMediaStorage(), upload_to='appointment_images/%Y/%m/', validators=[clinic.validators.validate_image_upload], verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='home_background',
            field=models.ImageField(blank=True, upload_to='clinic/branding/', validators=[clinic.validators.validate_image_upload], verbose_name='Фон сайту'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='clinic/branding/', validators=[clinic.validators.validate_image_upload], verbose_name='Логотип клініки'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='particle_image',
            field=models.ImageField(blank=True, upload_to='clinic/branding/particles/', validators=[clinic.validators.validate_image_upload], verbose_name='Зображення частинок'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='doctor_photos/', validators=[clinic.validators.validate_image_upload], verbose_name='Фото лікаря'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='clinic/gallery/', validators=[clinic.validators.validate_image_upload], verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='image',
            field=models.ImageField(upload_to='clinic/hero/', validators=[clinic.validators.validate_image_upload], verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='medicalserviceimage',
            name='image',
            field=models.ImageField(upload_to='service_photos/', validators=[clinic.validators.validate_image_upload], verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, upload_to='clinic/news/', validators=[clinic.validators.validate_image_upload], verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='patientrecordimage',
            name='image',
            field=models.ImageField(storage=clinic.storage.PrivateMediaStorage(), upload_to='patient_records/%Y/%m/', validators=[clinic.validators.validate_image_upload], verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='patient_photos/', validators=[clinic.validators.validate_image_upload], verbose_name='Фото профілю'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'patient'), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='unique_patient_profile_phone'),
        ),
        migrations.AddField(
            model_name='appointmentvideo',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='clinic.appointment', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Хто виконав дію'),
        ),
        migrations.AddField(
            model_name='medicalservicevideo',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='clinic.medicalservice', verbose_name='Послуга'),
        ),
        migrations.AddField(
            model_name='patientrecordvideo',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='clinic.patientrecordentry', verbose_name='Медичний запис'),
        ),
    ]
