# Generated by Django 6.0.6 on 2026-07-21 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_move_medical_media_to_private_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram chat ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name="Ім'я у Telegram")),
                ('is_active', models.BooleanField(default=True, verbose_name='Отримувати сповіщення')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Підключено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_connection', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Підключення Telegram',
                'verbose_name_plural': 'Підключення Telegram',
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Одноразовий код')),
                ('expires_at', models.DateTimeField(verbose_name='Діє до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Використано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Код підключення Telegram',
                'verbose_name_plural': 'Коди підключення Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=180, unique=True, verbose_name='Ключ події')),
                ('kind', models.CharField(max_length=40, verbose_name='Тип сповіщення')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('sent', 'Надіслано'), ('failed', 'Помилка')], default='pending', max_length=12, verbose_name='Статус')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Надіслано')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to='clinic.appointment', verbose_name='Запис на прийом')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Одержувач')),
            ],
            options={
                'verbose_name': 'Сповіщення Telegram',
                'verbose_name_plural': 'Сповіщення Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
