# Generated by Django 6.0.6 on 2026-07-26 14:47

import clinic.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0027_telegramconnection_telegramlinktoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='logo',
            field=models.FileField(blank=True, upload_to='clinic/branding/', validators=[clinic.validators.validate_logo_upload], verbose_name='Логотип клініки'),
        ),
    ]
