# Generated by Django 6.0.6 on 2026-08-02 19:56

import clinic.validators
import django.core.validators
from django.db import migrations, models


def clear_legacy_service_prices(apps, schema_editor):
    MedicalService = apps.get_model('clinic', 'MedicalService')
    MedicalService.objects.filter(approximate_price__gt=1_000_000).update(
        approximate_price=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0029_appointment_booked_for_other_and_card_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes_exact',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Тривалість прийому, хвилин'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_slots',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(144)], verbose_name='Кількість слотів'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(max_length=25, validators=[clinic.validators.validate_ukrainian_phone], verbose_name='Телефон пацієнта'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(max_length=2000, verbose_name='Причина звернення'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Інформація про лікаря'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=25, validators=[clinic.validators.validate_ukrainian_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='doctorpatientcard',
            name='notes',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Нотатки лікаря'),
        ),
        migrations.AlterField(
            model_name='doctorpatientcard',
            name='patient_phone',
            field=models.CharField(max_length=25, validators=[clinic.validators.validate_ukrainian_phone], verbose_name='Телефон пацієнта'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='approximate_price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000, message='Орієнтовна вартість не може перевищувати 1 000 000 грн.')], verbose_name='Орієнтовна вартість'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Опис послуги'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=models.TextField(max_length=10000, verbose_name='Текст новини'),
        ),
        migrations.AlterField(
            model_name='patientrecordentry',
            name='details',
            field=models.TextField(max_length=5000, verbose_name='Детальна інформація'),
        ),
        migrations.AlterField(
            model_name='patientrecordentry',
            name='recommendations',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Рекомендації пацієнту'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25, validators=[clinic.validators.validate_ukrainian_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='break_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Тривалість обіду, хвилин'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='slot_minutes',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(480)], verbose_name='Тривалість слота, хвилин'),
        ),
        migrations.RunPython(
            clear_legacy_service_prices,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='medicalservice',
            constraint=models.CheckConstraint(condition=models.Q(('approximate_price__isnull', True), ('approximate_price__lte', 1000000), _connector='OR'), name='service_price_at_most_one_million'),
        ),
    ]
