# Generated by Django 6.0.6 on 2026-09-28 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0030_alter_appointment_duration_minutes_exact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Одноразовий токен')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено'), ('expired', 'Термін дії минув')], default='pending', max_length=12, verbose_name='Статус')),
                ('expires_at', models.DateTimeField(verbose_name='Діє до')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Підтверджено або відхилено')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Вхід завершено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_login_challenges', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Підтвердження входу через Telegram',
                'verbose_name_plural': 'Підтвердження входу через Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
