# Generated by Django 6.0.6 on 2026-09-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0031_telegramloginchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Запит на відновлення доступу',
                'verbose_name_plural': 'Запити на відновлення доступу',
                'ordering': ['created_at'],
            },
        ),
    ]
