# Generated by Django 6.0.6 on 2026-09-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0033_recovery_requests_use_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordRecoveryRequest',
        ),
    ]
