# Generated by Django 6.0.6 on 2026-09-29 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0034_remove_password_recovery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecordentry',
            name='author_name',
            field=models.CharField(blank=True, max_length=320, verbose_name='Ім’я автора'),
        ),
        migrations.AddField(
            model_name='patientrecordentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_patient_records', to=settings.AUTH_USER_MODEL, verbose_name='Автор запису'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'Пацієнт'), ('doctor', 'Лікар'), ('clinic_admin', 'Адміністратор клініки')], max_length=20, verbose_name='Роль'),
        ),
    ]
